name: workflow-rdf
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - scipy
  - matplotlib
  - jupyterlab
  - pyyaml
  - pip:
    - atomrdf
    - tools4rdf
    - rdflib
    - pychromatic
